export enum UserPermission {
    BOOK_VIEW = 'BOOK_VIEW',
    BOOK_CREATE = 'BOOK_CREATE',
    BOOK_UPDATE = 'BOOK_UPDATE',
    BOOK_DELETE = 'BOOK_DELETE',

    USER_VIEW = 'USER_VIEW',
    USER_UPDATE_ROLE = 'USER_UPDATE_ROLE',

    LOAN_VIEW = 'LOAN_VIEW',
    LOAN_CREATE = 'LOAN_CREATE',
    LOAN_UPDATE = 'LOAN_UPDATE',
    LOAN_UPDATE_STATUS = 'LOAN_UPDATE_STATUS',

    PERMISSION_MANAGE = 'PERMISSION_MANAGE',
}